RUN_NAME: 'bloodMNIST_ours_Kmeans'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True
CLASS_NUM: 8
CLUSTERING_LABEL: 'labels_pred_blood_128.npy'

DATASET:
  NAME: 'bloodmnist'
  TRANSFORM_NAME: 'medMNIST'

MODEL:
  ARCH: 'resnet18'
  PRETRAIN_PATH: 'pretrained/blood_best_128.pth' 

USL:
  NUM_SELECTED_SAMPLES: 16
  KNN_K: 200
  SEEDS: [1,2,3,4,5]
