RUN_NAME: 'cifar10_ours_Kmeans'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True
CLASS_NUM: 10
CLUSTERING_LABEL: ''

DATASET:
  NAME: 'cifar10'
  TRANSFORM_NAME: 'CLD-cifar10'

MODEL:
  ARCH: 'ResNet18'
  PRETRAIN_PATH: ''

USL:
  NUM_SELECTED_SAMPLES: 40
  KNN_K: 400
  SEEDS: [1, 2, 3, 4, 5]
